### ISSUE TITLE
missing dependencies in debian package

### ISSUE THREAD

**Issue by zeroheure** [chunhualiu/hoptodesk#1]
Here's some bug reports regarding debian package for hoptodesk.

- There is a typo in /usr/share/appliactions ; should be /usr/share/applications
- missing dependencies on python3-pip and libxdo3

BTW, do you need help to set your repo in github ?

Best Regards
Xavier

**Comment by chunhualiu** [comment]
Hi, Xavier,
I am not the owner of HopToDesk.
I simply saved a copy here :)
It's from https://gitlab.com/hoptodesk/hoptodesk
And their website https://www.hoptodesk.com/

**Comment by zeroheure** [comment]
Thanks ! and sorry :-)

---
Librement,
Xavier Brochard ***@***.***
La liberté est à l'homme ce que les ailes sont à l'oiseau
(Jean-Pierre Rosnay)

Le 20.09.2022 18:25, chunhualiu a écrit :
> Hi, Xavier,
> I am not the owner of HopToDesk.
> I simply saved a copy here :)
> It's from https://gitlab.com/hoptodesk/hoptodesk
> And their website https://www.hoptodesk.com/
